services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - postgres_db
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres_db:5432/postgres?sslmode=disable
      PORT: 3030
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
